### ISSUE TITLE
probleme de db pour le delete de composer et type of piece

### ISSUE THREAD

**Issue by Califano9577** [Melomania-be/back#14]
delete de composer et type of piece:

-error: delete from "composers" where "id" = $1 - update or delete on table "composers" violates foreign key constraint "pieces_composer_id_foreign" on table "pieces"
-error: delete from "type_of_pieces" where "id" = $1 - update or delete on table "type_of_pieces" violates foreign key constraint "pieces_type_of_piece_id_foreign" on table "pieces"

j'ai encore ses erreurs qui bloquent avec la db de lundi

**Comment by melian-e** [comment]
### Solution temporaire tant que la bdd ne sera pas rebuild
localhost:8888 : table piece => alter foreign key pour chaque foreign key => passer on delete à "set NULL"

Ce problème sera réglé par #11
