### ISSUE TITLE
projects_controller et validator à adapter

### ISSUE THREAD

**Issue by JudithLco** [Melomania-be/back#5]
Les controller et validator de projects sont à adapter.
Données à traiter lors de la création d'un projet : 
- nom
- sectionGroup (créer ou sélectionner si existant)
- registration (toutes les informations que le participant devra renseigner à son inscription au projet, création de champs particuliers content_registration )
- répétitions
- pieces
- concerts

**Comment by melian-e** [comment]
sera réglé par #11
